# Generated by Django 3.2 on 2021-04-18 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=264)),
                ('LastName', models.CharField(max_length=264)),
                ('Email', models.EmailField(max_length=264, unique=True)),
            ],
        ),
    ]
